version: "3.9"

services:
  auto-gpt:
    image: popep/auto-gpt:1.0
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: redis
    volumes:
      - ./auto_gpt_workspace:/app/autogpt/auto_gpt_workspace
      - ./data:/app/data
      - ./logs:/app/logs
      ## uncomment following lines if you have / want to make use of these files
      #- ./azure.yaml:/app/azure.yaml
      #- ./ai_settings.yaml:/app/ai_settings.yaml
    depends_on:
      - redis

  redis:
    image: "redislabs/redisearch:latest"
    command: ["redis-server", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]
